name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build & run tests
        run: |
          docker compose -f docker-compose.local.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from cypress
